# Generated by Django 3.2.4 on 2021-06-08 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_merchant_merchant_logo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='merchant',
            name='merchant_logo',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
