# Generated by Django 3.2.4 on 2021-06-11 21:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_googletoken'),
    ]

    operations = [
        migrations.AlterField(
            model_name='googletoken',
            name='refresh_token',
            field=models.CharField(max_length=150, null=True),
        ),
    ]
