# Generated by Django 3.2.4 on 2021-06-12 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_alter_googletoken_refresh_token'),
    ]

    operations = [
        migrations.AddField(
            model_name='merchant',
            name='unique_email',
            field=models.EmailField(blank=True, default='example@example.com', max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='googletoken',
            name='refresh_token',
            field=models.CharField(max_length=150),
        ),
    ]
