# Generated by Django 3.2.4 on 2021-06-15 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_auto_20210612_1858'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='product_image',
            field=models.ImageField(default='/media/index.png', upload_to='frontend/static/images/product_picture'),
        ),
    ]
