# Generated by Django 3.2.4 on 2021-06-20 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_alter_products_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='merchant_logo',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
