# Generated by Django 3.2.4 on 2021-06-20 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_products_merchant_logo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='sub_category',
            field=models.ManyToManyField(blank=True, null=True, related_name='_api_category_sub_category_+', to='api.Category'),
        ),
    ]
