# Generated by Django 3.2.4 on 2021-06-21 11:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0021_auto_20210621_1424'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='userproducts',
            options={'verbose_name_plural': 'User Products'},
        ),
        migrations.RemoveField(
            model_name='user',
            name='cart',
        ),
        migrations.AddField(
            model_name='user',
            name='cart',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.userproducts'),
        ),
    ]
