# Generated by Django 3.2.4 on 2021-06-21 11:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0022_auto_20210621_1540'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userproducts',
            name='product',
        ),
        migrations.AddField(
            model_name='userproducts',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.products'),
        ),
        migrations.AlterField(
            model_name='userproducts',
            name='quantity',
            field=models.IntegerField(default=0),
        ),
    ]
