# Generated by Django 3.2.4 on 2021-06-26 12:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0026_alter_usercart_quantity'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='sub_sub_category',
        ),
        migrations.RemoveField(
            model_name='subcategory',
            name='description',
        ),
        migrations.RemoveField(
            model_name='subsubcategory',
            name='description',
        ),
        migrations.AddField(
            model_name='products',
            name='sub_category',
            field=models.ManyToManyField(blank=True, null=True, to='api.SubCategory'),
        ),
        migrations.AddField(
            model_name='products',
            name='sub_sub_category',
            field=models.ManyToManyField(blank=True, null=True, to='api.SubSubCategory'),
        ),
        migrations.AddField(
            model_name='subcategory',
            name='sub_category',
            field=models.ManyToManyField(blank=True, null=True, to='api.SubSubCategory'),
        ),
        migrations.AlterField(
            model_name='category',
            name='sub_category',
            field=models.ManyToManyField(blank=True, null=True, to='api.SubCategory'),
        ),
        migrations.RemoveField(
            model_name='products',
            name='category',
        ),
        migrations.AddField(
            model_name='products',
            name='category',
            field=models.ManyToManyField(blank=True, null=True, to='api.Category'),
        ),
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='usercart',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cart_product', to='api.products'),
        ),
        migrations.AlterField(
            model_name='usercart',
            name='username',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
