# Generated by Django 3.2.4 on 2021-06-26 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0027_auto_20210626_1713'),
    ]

    operations = [
        migrations.RenameField(
            model_name='subcategory',
            old_name='sub_category',
            new_name='sub_sub_category',
        ),
        migrations.AlterField(
            model_name='category',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
