# Generated by Django 3.2.4 on 2021-06-26 13:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0028_auto_20210626_1744'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Category',
            new_name='Categories',
        ),
        migrations.AlterModelOptions(
            name='categories',
            options={},
        ),
    ]
