# Generated by Django 3.2.4 on 2021-07-02 15:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0031_auto_20210701_1503'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='useraddress',
            options={'get_latest_by': ['address']},
        ),
    ]
