# Generated by Django 3.2.4 on 2021-07-04 11:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0032_alter_useraddress_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='date_received',
        ),
        migrations.RemoveField(
            model_name='user',
            name='is_received',
        ),
        migrations.CreateModel(
            name='Orders',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(blank=True, max_length=50, null=True)),
                ('is_received', models.BooleanField(default=False)),
                ('date_received', models.DateTimeField(blank=True, null=True)),
                ('date_delivered', models.DateTimeField(blank=True, null=True)),
                ('address', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.useraddress')),
                ('order', models.ManyToManyField(blank=True, null=True, to='api.UserCart')),
            ],
        ),
        migrations.AddField(
            model_name='merchant',
            name='orders',
            field=models.ManyToManyField(blank=True, null=True, to='api.Orders'),
        ),
        migrations.AddField(
            model_name='user',
            name='orders',
            field=models.ManyToManyField(blank=True, null=True, to='api.Orders'),
        ),
    ]
