# Generated by Django 3.2.4 on 2021-07-05 11:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0034_auto_20210704_1708'),
    ]

    operations = [
        migrations.AddField(
            model_name='usercart',
            name='address',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.useraddress'),
        ),
        migrations.AlterField(
            model_name='categories',
            name='sub_category',
            field=models.ManyToManyField(blank=True, to='api.SubCategory'),
        ),
        migrations.AlterField(
            model_name='merchant',
            name='orders',
            field=models.ManyToManyField(blank=True, to='api.Orders'),
        ),
        migrations.AlterField(
            model_name='orders',
            name='order',
            field=models.ManyToManyField(blank=True, to='api.UserCart'),
        ),
        migrations.AlterField(
            model_name='products',
            name='category',
            field=models.ManyToManyField(blank=True, to='api.Categories'),
        ),
        migrations.AlterField(
            model_name='products',
            name='sub_category',
            field=models.ManyToManyField(blank=True, to='api.SubCategory'),
        ),
        migrations.AlterField(
            model_name='products',
            name='sub_sub_category',
            field=models.ManyToManyField(blank=True, to='api.SubSubCategory'),
        ),
        migrations.AlterField(
            model_name='subcategory',
            name='sub_sub_category',
            field=models.ManyToManyField(blank=True, to='api.SubSubCategory'),
        ),
        migrations.AlterField(
            model_name='user',
            name='cart',
            field=models.ManyToManyField(blank=True, to='api.UserCart'),
        ),
        migrations.AlterField(
            model_name='user',
            name='orders',
            field=models.ManyToManyField(blank=True, to='api.Orders'),
        ),
    ]
