# Generated by Django 3.2.4 on 2021-07-05 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0035_auto_20210705_1552'),
    ]

    operations = [
        migrations.AlterField(
            model_name='merchant',
            name='orders',
            field=models.ManyToManyField(blank=True, to='api.UserCart'),
        ),
    ]
