# Generated by Django 3.2.4 on 2021-07-04 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('IDpay', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymentid',
            name='username',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
