# Generated by Django 3.2.4 on 2021-07-04 11:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('IDpay', '0002_paymentid_username'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='paymentid',
            options={'verbose_name_plural': 'Payment ID'},
        ),
        migrations.AlterModelOptions(
            name='paymentinfo',
            options={'verbose_name_plural': 'Payment Info'},
        ),
    ]
